DATABASE_USER = 'postgres'
DATABASE_PASSWORD = 'famished'
DATABASE_NAME = 'postgres'
DATABASE_HOST = 'localhost'
DATABASE_PORT = 5432

"""
DATABASE_USER = 'fdggxsxy'
DATABASE_PASSWORD = 'fblPAJWqVJO-YUs7MyV6Itaje-NMrEA5'
DATABASE_NAME = 'fdggxsxy'
DATABASE_HOST = 'flora.db.elephantsql.com'
DATABASE_PORT = 5432
"""

# ADMIN KONTO
DATABASE_USER_A = 'ADMIN_ACC'
DATABASE_PASSWORD_A = 'admin1'

#USER KONTO
DATABASE_USER_U = 'USER_ACC'
DATABASE_PASSWORD_U = 'user1'

