

# global config
DATABASE_NAME = ''
DATABASE_HOST = ' '
DATABASE_PORT = 5432

# ADMIN
DATABASE_USER_ADMIN = ''
DATABASE_PASSWORD_ADMIN = ''

# USER
DATABASE_USER_USER = ''
DATABASE_PASSWORD_USER = ''





# baza online
DATABASE_USER = 'fdggxsxy'
DATABASE_PASSWORD = 'fblPAJWqVJO-YUs7MyV6Itaje-NMrEA5'
DATABASE_NAME = 'fdggxsxy'
DATABASE_HOST = 'flora.db.elephantsql.com'
DATABASE_PORT = 5432
