DATABASE_USER = 'postgres'
DATABASE_PASSWORD = 'famished'
DATABASE_NAME = 'postgres'
DATABASE_HOST = 'localhost'
DATABASE_PORT = 5432

"""
DATABASE_USER = ''
DATABASE_PASSWORD = ''
DATABASE_NAME = ''
DATABASE_HOST = ''
DATABASE_PORT = 0
"""

# ADMIN KONTO
DATABASE_USER_A = 'ADMIN_ACC'
DATABASE_PASSWORD_A = 'admin1'

#USER KONTO
DATABASE_USER_U = 'USER_ACC'
DATABASE_PASSWORD_U = 'user1'

